#!/usr/bin/perl -w

#
# Author: 
#   Donovan C. Young
#
# Description:
# -----------
#
# Implementation Notes:
# ---------------------
#   Depends on tapelist.pl which actually performs the tape inventory
#
########################################################################

require 5.004;

use POSIX;

use strict;
use vars qw($PROGNAME $CHECKNAME $AUTHOR $TIMEOUT %ECODES $VERSION);
use vars qw($opt_w $opt_c $opt_s $verbose);

#
# common variables
#
## Change These to suite your needs##
$PROGNAME  = qq(check_scratch_tapes);
$CHECKNAME = qq($PROGNAME);  # In case this needs to be different
$AUTHOR    = qq(Donovan C. Young);
$VERSION   = "1.0"; # Program version

$TIMEOUT  = qq(15);
%ECODES   = (
              'OK'        => 0,
              'WARNING'   => 1,
              'CRITICAL'  => 2,
              'UNKNOWN'   => 3,
              'DEPENDENT' => 4
            );

#
# Process Options
#
use Getopt::Long;
Getopt::Long::Configure('bundling', 'no_ignore_case');
GetOptions (
              "V|version"     => \&version,
              "h|help"        => \&help,
              "v|verbose"     => \$verbose,
              "w|warning=i"   => \$opt_w,
              "c|critical=i"  => \$opt_c,
           );

#
# Subroutines
#
sub print_usage {
    print "Usage: $PROGNAME [-vh] [-w warn] [-c crit]\n";
}

sub print_help {
    print "\nWritten by $AUTHOR\n\nPerl plugin for Nagios\n\n";
    print_usage();
    print "
-v, --verbose
   Return additional information. 
   Intended as a command-line aid, not recommended for Nagios script usage.

-w, --warning=INTEGER
   Level at which we should issue a warning.  If omitted, no warning is generated. 

-c, --critical=INTEGER
   Level at which we should issue a critical alert.

";
}

sub revision {
    my $commandName = $PROGNAME;
    my $pluginRevision = $VERSION;
    print "$commandName $pluginRevision\n";
    print " The nagios plugins come with ABSOLUTELY NO WARRANTY. You may redistribute\n";
    print " copies of the plugins under the terms of the GNU General Public License.\n";
    print " For more information about these matters, see the file named COPYING.\n";
}

sub version {
    &revision;
    exit $ECODES{'OK'};
}

sub help {
    &print_help;
    exit $ECODES{'OK'};
}

sub myexit {
        my ( $state, $message, $perfdata ) = @_;
        ( $state )   || ( $state   = q(UNKNOWN) );
        ( $message ) || ( $message = q() );

        printf "%s %s", $CHECKNAME, $state;
        if ( $message ) { printf " - %s", $message; }

        if ( defined $perfdata ) { printf "|%s", $perfdata; }

        print "\n";
        if ( defined $ECODES{$state} ) { exit $ECODES{$state}; }
        exit $ECODES{'UNKNOWN'};
}

#
# Set our defaults
#
my $checkstate  = q(UNKNOWN);   # Set to the ECODE to return (OK, WARNING, or CRITICAL).
my $checkresult = q();          # Verbose message to return
my $checkdata   = undef;        # Nagios "Performance data"

if ( not defined $opt_w or not defined $opt_c ) {
    myexit( 'UNKNOWN', 'Please provide -w and -c options', undef );
}

# Main()
MAIN: {
    my $checkcmd = q(/usr/local/bin/tapelist.pl);
    if ( ! -x $checkcmd ) { myexit( 'DEPENDENT', "$checkcmd not found or is not executable", undef ); }

    my $checkdata = qx(sudo $checkcmd --nagios) or
        myexit( 'DEPENDENT', "Unable to run $checkcmd", undef );

    my ($tapes, $full, $active, $scratch ) = ( $checkdata =~ /tapes:(\d+); full:(\d+); active:(\d+); scratch:(\d+)/ ) or
        myexit( 'DEPENDENT', "$checkcmd did not return a valid result", "Return: $checkdata" );

    if ( $scratch gt $opt_w ) { $checkstate = q(OK);       $checkresult = qq($scratch scratch tapes available); }
    if ( $scratch le $opt_w ) { $checkstate = q(WARNING);  $checkresult = qq(Only $scratch scratch tapes available); }
    if ( $scratch le $opt_c ) { $checkstate = q(CRITICAL); $checkresult = qq($opt_c or less scratch tapes available \($scratch\)); }

    #
    # Exit based on current state
    #
    myexit( $checkstate, $checkresult, $checkdata );
}

#======= end script =======
1;
